#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.

echo "--build hook called--"
echo "build hook: IMAGE_NAME '$IMAGE_NAME'"
echo "build hook: DOCKERFILE_PATH '$DOCKERFILE_PATH'"
echo "build hook: CACHE_TAG '$CACHE_TAG'"
echo "build hook: DOCKER_TAG '$DOCKER_TAG'"
echo "build hook: DOCKER_REPO '$DOCKER_REPO'"
echo "build hook: SOURCE_BRANCH '$SOURCE_BRANCH'"
echo "build hook: SOURCE_COMMIT '$SOURCE_COMMIT'"

# extracts the PHP version and the ONA version from the docker-tag
# the format must be `[ONA]-php[PHP]` or `[ONA]`
#  + master-php7
#  + v18.1.1-php7.2
#  + v18.1.1
# There seems to be a bug and $CACHE_TAG is empty. Thats why we use $IMAGE_NAME
# here. See https://forums.docker.com/t/build-env-var-cache-tag-not-passed-to-post-push-hook/41747
php_included="$(echo "$IMAGE_NAME" | sed 's,[^:]*:[^\-]*\-\(php\).*,\1,')"
echo "build hook: php_included '$php_included'"

PHP_VERSION="$(echo "$IMAGE_NAME" | sed 's,[^:]*:[^\-]*\-php\([^\-]*\).*,\1,')"
echo "build hook: PHP_VERSION '$PHP_VERSION'"

ONA_VERSION="$(echo "$IMAGE_NAME" | sed 's,[^:]*:\([^\-]*\).*,\1,')"
echo "build hook: ONA_VERSION '$ONA_VERSION'"

build_args=''

# This will fetch the commit hash of ONA_VERSION. If ONA_VERSION is already a
# commit hash, it will fetch the full length. Note that there are multiple "sha"
# fileds in the json return, and it is assumed that the commit sha is the firt
# result. xargs will trim whitespaces.
APP_VCS_REF="$(curl --silent https://api.github.com/repos/opennetadmin/ona/commits/master | sed -En 's/"sha": "(.*)",/\1/p' | head --lines=1 | xargs)"

if [ "$php_included" == "php" ]; then
    build_args=(${build_args} --build-arg PHP_VERSION="$PHP_VERSION")
fi

docker build --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
            --build-arg VCS_REF=$(git rev-parse --short HEAD) \
            ${build_args[@]} \
            --build-arg ONA_VERSION="$ONA_VERSION" \
            --build-arg APP_VCS_REF="$APP_VCS_REF" \
            -f $DOCKERFILE_PATH -t $IMAGE_NAME .

